### ISSUE TITLE
 执行raw_datasets = load_dataset(extension, data_files=data_files) 报错,你是如何解决的?

### ISSUE THREAD

**Issue by apexg** [rtmaww/EntLM#2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/load.py", line 711, in load_dataset
    module_path, hash, resolved_file_path = prepare_module(
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/load.py", line 354, in prepare_module
    raise FileNotFoundError(
FileNotFoundError: Couldn't find file locally at lhoestq/demo1/demo1.py, or remotely at https://huggingface.co/datasets/lhoestq/demo1/resolve/main/demo1.py. Please provide a valid dataset name
>>> raw_datasets = load_dataset('json', data_files='/usr/local/notebook_dir/EntLM/dataset/conll/5shot/1.json')
Using custom data configuration default-eaef8de8e7268fcc
Downloading and preparing dataset json/default (download: Unknown size, generated: Unknown size, post-processed: Unknown size, total: Unknown size) to /root/.cache/huggingface/datasets/json/default-eaef8de8e7268fcc/0.0.0/83d5b3a2f62630efc6b5315f00f20209b4ad91a00ac586597caee3a4da0bef02...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/load.py", line 745, in load_dataset
    builder_instance.download_and_prepare(
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/builder.py", line 574, in download_and_prepare
    self._download_and_prepare(
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/builder.py", line 630, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/packaged_modules/json/json.py", line 47, in _split_generators
    data_files = dl_manager.download_and_extract(self.config.data_files)
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 287, in download_and_extract
    return self.extract(self.download(url_or_urls))
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/utils/download_manager.py", line 261, in extract
    extracted_paths = map_nested(
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/utils/py_utils.py", line 195, in map_nested
    return function(data_struct)
  File "/root/.jupyter/Pytorch-1.8.1/lib/python3.8/site-packages/datasets/utils/file_utils.py", line 307, in cached_path
    and not tarfile.is_tarfile(output_path)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 2466, in is_tarfile
    t = open(name)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 1599, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 1728, in xzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 1647, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 1510, in __init__
    self.firstmember = self.next()
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 2313, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/python3/lib/python3.8/tarfile.py", line 1102, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/local/python3/lib/python3.8/lzma.py", line 206, in read
    return self._buffer.read(size)
  File "/usr/local/python3/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/python3/lib/python3.8/_compression.py", line 96, in read
    if self._decompressor.needs_input:
AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input'

**Comment by apexg** [comment]
是因为python版本的问题,我原来的是3.8,下降为3.7.5就可以了
